export const STAFF_PERMISSIONS = {
  VIEW_USERS: "VIEW_USERS",
  VIEW_TRANSACTIONS: "VIEW_TRANSACTIONS",
  VIEW_VERIFICATIONS: "VIEW_VERIFICATIONS",
  VIEW_SUPPORT: "VIEW_SUPPORT",
  MANAGE_STAFF: "MANAGE_STAFF",
  MANAGE_PRICING: "MANAGE_PRICING",
} as const;

export type StaffPermission =
  (typeof STAFF_PERMISSIONS)[keyof typeof STAFF_PERMISSIONS];